import assert from 'node:assert/strict';
import { analyzePayload, payloadPaths, valueAt } from '../lib/workbench/payloadEngine.ts';
import { searchScore, rankEntries } from '../lib/workbench/discovery.ts';
import { validDocument, remoteDocument, parseStore, makeRecord } from '../lib/workspaces/model.ts';
import { mergeRemote } from '../lib/workspaces/sync.ts';
import { inferSchema } from '../lib/workbench/jsonSchema.ts';

const tricky = JSON.parse('{"__proto__":{"x":1},"a/b":{"~key":false},"":null}');
assert.equal(valueAt(tricky, ['__proto__', 'x']), 1);
assert.throws(() => valueAt({}, ['toString']));
assert.equal(payloadPaths(['a/b', '~key']).pointer, '/a~1b/~0key');
assert.equal(payloadPaths(['a.b']).javascript, 'payload["a.b"]');
const wide = analyzePayload(Array.from({ length: 30_000 }, (_, i) => i), 10);
assert.equal(wide.nodes.length, 20_000);
assert.equal(wide.partial, true);
let deep: unknown = null;
for (let i = 0; i < 10_000; i++) deep = { child: deep };
const deepAnalysis = analyzePayload(deep, 10);
assert.equal(deepAnalysis.depth, 64);
assert.equal(deepAnalysis.partial, true);
assert.equal(analyzePayload({ a: null, b: [true, 3] }, 10).nodes.length, 5);
const entries = [{ id: 'payload', label: 'Payload Lab', hint: 'JSON', keywords: 'inspect' }, { id: 'schema', label: 'JSON Schema', hint: '' }];
assert.equal(rankEntries(entries, 'paylod')[0].id, 'payload');
assert.equal(searchScore(entries[0], 'nonexistent'), -1);
assert.equal(rankEntries(entries, '', ['schema'])[0].id, 'schema');
const preset = { id: 'one', version: 1 as const, toolId: 'payload', name: 'Test', settings: {}, content: { payload: 'secret' }, syncContent: false };
const row = makeRecord(preset, 'presets');
assert.equal('content' in remoteDocument(row), false);
assert.equal('content' in remoteDocument({ ...row, document: { ...preset, syncContent: true } }), true);
assert.equal(validDocument(preset, 'presets'), true);
assert.equal(validDocument({ ...preset, content: { payload: 7 } }, 'presets'), false);
assert.equal(validDocument({ ...preset, settings: { payload: 'must-not-upload' } }, 'presets'), false);
assert.equal(validDocument({ id: 'a', name: 'x', version: 1, entries: [{ id: 'a', resourceId: 'javascript:alert(1)' }] }, 'workspaces'), false);
assert.throws(() => parseStore({ version: 2, records: [] }));
assert.equal(parseStore({ version: 1, records: [row] }).records.length, 1);
const remote = { ...row, revision: 2, dirty: false, document: { ...preset, name: 'Other device' } };
const merged = mergeRemote([row], [remote]);
assert.equal(merged[0].document.name, 'Test');
assert.equal(merged[0].conflict?.name, 'Other device');
assert.equal(merged[0].revision, 2);
assert.equal(mergeRemote([{ ...row, dirty: false }], [remote])[0].document.name, 'Other device');
const schema = inferSchema([{ a: 1 }, { b: null }]);
assert.equal((schema.items as { anyOf: unknown[] }).anyOf.length, 2);
assert.deepEqual(inferSchema({ a: null }).required, ['a']);
assert.equal(payloadPaths(['items', 0]).jsonpath, '$["items"][0]');
console.log('workspaces: search, JSON bounds, safe paths, validation, content consent passed');
